const autos = [
	{
		marca: 'BMW',
		modelo: 'M3 ',
		year: 2020,
		precio: '$9.000.000',
		puertas: 5,
		color: 'Azul eléctrico',
		transmision: 'automatico',
		Kilometros: '19046 Km',
		imagen: 'img/BMW_m3.png'
	},
	{ 
        marca: 'Audi', 
        modelo: 'A4', 
        year: 2020, 
        precio: '$9.500.000', 
        puertas: 5, 
        color: 'Gris plomo', 
        transmision: 'automatico', 
		Kilometros: '20386 Km',
		imagen: 'img/AUDI_a4.png'
    },
	{
		marca: 'Ford',
		modelo: 'Mustang',
		year: 2015,
		precio: '$8.000.000',
		puertas: 3,
		color: 'Blanco',
		transmision: 'automatico',
		Kilometros: '64025 Km',
		imagen: 'img/MUSTANG_shelby.png'
	},
	{
		marca: 'Renault',
		modelo: 'Fluence 2.0',
		year: 2015,
		precio: '$2.000.000',
		puertas: 5,
		color: 'Blanco',
		transmision: 'manual',
		Kilometros: '70234 Km',
		imagen: 'img/Fluence_blanco.png'
	},
	{ 
        marca: 'Audi', 
        modelo: 'A6', 
        year: 2015, 
        precio: '$3.500.000', 
        puertas: 5, 
        color: 'Negro', 
        transmision: 'automatico',
		Kilometros: '85328 Km',
		imagen:'img/Audi_a6_negro.png' 
    },
	{
		marca: 'Citroen',
		modelo: 'DS3',
		year: 2015,
		precio: '$2.800.000',
		puertas: 3,
		color: 'Blanco',
		transmision: 'manual',
		Kilometros: '59302 Km',
		imagen: 'img/DS3_blanco.png'
	},
	{
		marca: 'BMW',
		modelo: '530',
		year: 2012,
		precio: '$4.200.000',
		puertas: 5,
		color: 'Azul',
		transmision: 'automatico',
		Kilometros: '103292 Km',
		imagen:'img/BMW_530_azul.png'
	},
	{
		marca: 'Mercedes Benz',
		modelo: 'Clase C',
		year: 2015,
		precio: '$4.500.000',
		puertas: 5,
		color: 'Azul',
		transmision: 'automatico',
		Kilometros: '73420 Km',
		imagen:'img/MB_claseC.png'
	},
	{
		marca: 'Peugeot',
		modelo: '3008',
		year: 2018,
		precio: '$4.000.000',
		puertas: 5,
		color: 'Rojo',
		transmision: 'manual',
		Kilometros: '66874 Km',
		imagen:'img/3008_rojo.png'
	},
	{ 
        marca: 'Ford', 
        modelo: 'Mustang', 
        year: 2019, 
        precio: '$5.600.000', 
        puertas: 3, 
        color: 'Negro', 
        transmision: 'manual',
		Kilometros: '53208 Km',
		imagen:'img/Mustang_negro.png' 
    },
	{
		marca: 'Peugeot',
		modelo: '208 GTI',
		year: 2020,
		precio: '$4.500.000',
		puertas: 5,
		color: 'Blanco',
		transmision: 'automatico',
		Kilometros: '45897 Km',
		imagen:'img/208_gti.png'
	},
	{ 
        marca: 'Audi', 
        modelo: 'A3', 
        year: 2017, 
        precio: '$3.100.000', 
        puertas: 5, 
        color: 'Negro', 
        transmision: 'manual',
		Kilometros: '21078 Km',
		imagen:'img/AudiA3_negro.png' 
    },
	{
		marca: 'Peugeot',
		modelo: '2008',
		year: 2020,
		precio: '$3.400.000',
		puertas: 5,
		color: 'Blanco',
		transmision: 'manual',
		Kilometros: '22944 Km',
		imagen:'img/2008_blanco.png'
	},
	{
		marca: 'Mercedes Benz',
		modelo: 'Clase C',
		year: 2018,
		precio: '$3.800.000',
		puertas: 3,
		color: 'Gris',
		transmision: 'automatico',
		Kilometros: '17833 Km',
		imagen:'img/MB_claseC_gris.png'
	},
	{
		marca: 'BMW',
		modelo: '523',
		year: 2013,
		precio: '$3.200.000',
		puertas: 5,
		color: 'Negro',
		transmision: 'automatico',
		Kilometros: '23874 Km',
		imagen:'img/BMW_523.png'
	},
	{ 
        marca: 'Ford', 
        modelo: 'Focus Ghia', 
        year: 2014, 
        precio: '$1.300.000', 
        puertas: 3, 
        color: 'Negro', 
        transmision: 'manual',
		Kilometros: '55982 Km',
		imagen:'img/Focus3P.png' 
    },
	{
		marca: 'Ford',
		modelo: 'Mondeo Ghia',
		year: 2015,
		precio: '$2.800.000',
		puertas: 5,
		color: 'Azul',
		transmision: 'automatico',
		Kilometros: '33907 Km',
		imagen:'img/Mondeo_azul.png'
	},
	{
		marca: 'BMW',
		modelo: '328',
		year: 2015,
		precio: '$3.200.000',
		puertas: 5,
		color: 'Blanco',
		transmision: 'automatico',
		Kilometros: '9844 Km',
		imagen:'img/328_blanco.png'
	},
	{
		marca: 'BMW',
		modelo: '323 M3',
		year: 2017,
		precio: '$4.200.000',
		puertas: 3,
		color: 'Gris',
		transmision: 'automatico',
		Kilometros: '15822 Km',
		imagen:'img/323_M3.png'
	},
	{
		marca: 'Mercedes Benz',
		modelo: 'Clase E',
		year: 2018,
		precio: '$4.000.000',
		puertas: 5,
		color: 'Blanco',
		transmision: 'automatico',
		Kilometros: '6744 Km',
		imagen:'img/MB_claseE.png'
	},
	{ 
        marca: 'Audi', 
        modelo: 'A1', 
        year: 2016, 
        precio: '$2.800.000', 
        puertas: 5, 
        color: 'Blanco', 
        transmision: 'automatico',
		Kilometros: '5222 Km',
		imagen:'img/Audi_A1.png' 
    }
];
